name: Startups
favicon: null
layout_spectrum: 0.7352126548066735
typography_spectrum: 0.40106119122356176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5323121594265103
  lightness: 0.8819244413170964
  saturation: 0.33061868231743574
  rhythmicContrast: 0.5223225043155253
purpose: []
